### ISSUE TITLE
Ajouter un README.md pour ce projet

### ISSUE THREAD

**Issue by jonquet** [sifrproject/multilingual_mappings#3]
@AminaANNANE Pourrez tu ajouter une petite description de ce qu'est ce projet et inclure un lien vers notre papier WIMS

**Comment by AminaANNANE** [comment]
@jonquet Oui, juste pour que je sois sûre, par projet vous voulez dire la réconciliation de mappings multilingues (ou le projet SIFR)? Aussi, vous voulez la description en anglais ou en français?

**Comment by jonquet** [comment]
Plutôt en anglais. 
Seulement pour le projet mappings multilingues... celui /multilingual_mappings dans GitHub.
Faut juste faire un petit README.md qui dise ce que le projet fait.

**Comment by jonquet** [comment]
Completed and closed.
