### ISSUE TITLE
Il manque 2 fichiers de mappings dans les resultats pour MDRFRE et SNMIFRE

### ISSUE THREAD

**Issue by jonquet** [sifrproject/multilingual_mappings#4]
On vient de faire le point avec @twktheainur  sur les résultats pour les réutiliser dans une autre tache 👍 https://github.com/sifrproject/sifr_project_java_ontology_processing/issues/3

Et il nous manque ces 2 fichiers. Pourrez tu les mettre ?

**Comment by AminaANNANE** [comment]
Bonjour

J'ai les fichiers sur google drive, je n'ai pas pu les uploader car ils ont une taille qui dépasse la taille max d'un fichier sur github (un message d'erreur s'affiche!)
@twktheainur, je peux vous donner les fichiers sur un flash disk si vous voulez?

Amina.

**Comment by twktheainur** [comment]
Bonjour @AminaANNANE,
 Il n'y pas de soucis. Dis moi quand ça t'arrange que je les récupère. 

Andon

**Comment by AminaANNANE** [comment]
Voici le lien du dossier qui comporte tous les mappings https://drive.google.com/drive/folders/0B-U8RqCVX50yWFFBWElROXg2eVk?usp=sharing
dites moi si vous n'arrivez pas à y accéder

**Comment by twktheainur** [comment]
@AminaANNANE Super, j'ai pu les récupérer. Je pense que je vais essayer de les pusher sur le GitHub après compression avec gzip, ça devrais bien réduire sur des fichiers texte de ce style

**Comment by AminaANNANE** [comment]
@twktheainur  la compression est une bonne idée, j'ai dû penser à ça!

**Comment by twktheainur** [comment]
@AminaANNANE J'ai fait les modifications, mais je ne suis pas autorisé à faire de push sur ce projet. Est que tu peux m'ajouter?

**Comment by AminaANNANE** [comment]
@twktheainur c'est fait, je les ai uploadé tous les deux merci pour l'idée de compression :)
